# Generated by Django 2.2.28 on 2024-02-06 14:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rango', '0004_auto_20240206_1313'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='wesbite',
            new_name='website',
        ),
    ]
